USE  HeThongSoLienLac
GO

CREATE PROCEDURE DangNhapTruong
@TaiKhoan VARCHAR(100),
@MatKhau VARCHAR(200)
AS
SELECT * FROM dbo.TaiKhoanTruong WHERE TaiKhoan = @TaiKhoan AND MatKhau = CONVERT(VARCHAR(32),HASHBYTES('MD5', @MatKhau),2)
GO

CREATE PROCEDURE LayDanhSachTheoLop
@IDLop INT
AS	
BEGIN
    SELECT * FROM dbo.ThongTinHS WHERE IDLop = @IDLop
END
GO	

CREATE PROCEDURE UpdateTKQLyHS
@ID INT,
@IDTK INT
AS	
BEGIN
    UPDATE dbo.ThongTinHS
	SET	IDTaiKhoan = @IDTK
	WHERE ID = @ID
END
GO	

CREATE PROCEDURE LaySTTDiemDanh
@IDHS INT,
@NgayNghi DATE
AS	
BEGIN
    SELECT * FROM dbo.DiemDanh WHERE IDHocSinh = @IDHS AND  NgayNghi = @NgayNghi
END
GO