CREATE DATABASE ServerTest
GO	

USE	ServerTest
GO	

CREATE TABLE TaiKhoanTruong
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TaiKhoan VARCHAR(100),
	MatKhau VARCHAR(500),
	Loai BIT DEFAULT 0
)
GO

CREATE TABLE TaiKhoanPH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TaiKhoan VARCHAR(100),
	MatKhau VARCHAR(500)
)
GO

CREATE TABLE MonHoc
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TenMon NVARCHAR(200),
	LoaiDiem BIT DEFAULT 1
)
GO

CREATE TABLE Lop
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TenLop NVARCHAR(50)
)
GO

CREATE TABLE ThongTinGV
(
	IDTKT INT PRIMARY KEY,
	TenGV NVARCHAR(200),
	SDT VARCHAR(12),
	IDMonHoc INT,

	FOREIGN KEY (IDTKT) REFERENCES dbo.TaiKhoanTruong(ID),
	FOREIGN KEY (IDMonHoc) REFERENCES dbo.MonHoc(ID)
)
GO

CREATE TABLE LoaiHocSinh
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TenLoai NVARCHAR(200)
)

CREATE TABLE ThongTinHS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ten NVARCHAR(200),
	NgaySinh DATE,
	GioiTinh BIT,
	NoiSinh NVARCHAR(250),
	DanToc NVARCHAR(100),
	TonGiao NVARCHAR(100),
	IDLop INT,
	IDLoaiHocSinh INT,
	

	FOREIGN KEY (IDLop) REFERENCES dbo.Lop(ID),
	FOREIGN KEY (IDLoaiHocSinh) REFERENCES dbo.LoaiHocSinh(ID)
)
GO

CREATE TABLE ThongTinPHHS
(
	IDHocSinh INT PRIMARY KEY,
	TenMe NVARCHAR(150),
	SDTMe VARCHAR(12),
	TenBo NVARCHAR(150),
	SDTBo VARCHAR(12),

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO

CREATE TABLE LienKetPHvsHS
(
	IDHocSinh INT PRIMARY KEY,
	IDTaiKhoan INT,

	FOREIGN KEY(IDHocSinh) REFERENCES dbo.ThongTinHS(ID),
	FOREIGN KEY (IDTaiKhoan) REFERENCES dbo.TaiKhoanPH(ID)
)
GO	 

CREATE TABLE DiemDanh
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	NgayNghi DATE,
	Phep BIT DEFAULT 0,

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO

CREATE TABLE XinPhep
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	NghiTu DATE,
	NghiDen DATE,
	SoNgayNghi INT,

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO

CREATE TABLE CupHoc
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	Ngay DATE,
	Tiet INT,

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO

CREATE TABLE LoaiDiem
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TenLoaiDiem NVARCHAR(50)
)
GO 

CREATE TABLE BangDiem
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	IDMonHoc INT,
	IDLoaiDiem INT,
	NgayNhap DATE,
	Diem INT,
	HocKyI BIT DEFAULT 1,

	FOREIGN KEY (IDHocSinh) REFERENCES  dbo.ThongTinHS(ID),
	FOREIGN KEY (IDMonHoc) REFERENCES dbo.MonHoc(ID),
	FOREIGN KEY (IDLoaiDiem) REFERENCES dbo.LoaiDiem(ID)

)
GO 

CREATE TABLE HanhKiem
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	Loai NVARCHAR(20),
	HocKyI BIT DEFAULT 1,

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO

CREATE TABLE ThoiKhoaBieu
(
	IDLop INT,
	Thu INT,
	Tiet INT,
	IDMonHoc INT,

	FOREIGN KEY (IDLop) REFERENCES  dbo.Lop(ID),
	FOREIGN KEY (IDMonHoc) REFERENCES dbo.MonHoc(ID)
)
GO

CREATE TABLE LoaiThongBao
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TenThongBao NVARCHAR(100)
)
GO 

CREATE TABLE ThongBaoTruong
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NoiDung NVARCHAR(MAX),
	Ngay DATE,
	IDLoaiThongBao INT,

	FOREIGN KEY (IDLoaiThongBao) REFERENCES dbo.LoaiThongBao(ID)
)
GO	

CREATE TABLE ThongBaoLop
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDLop INT,
	NoiDung NVARCHAR(MAX),
	Ngay DATE,
	IDLoaiThongBao INT,

	FOREIGN KEY (IDLoaiThongBao) REFERENCES dbo.LoaiThongBao(ID),
	FOREIGN KEY (IDLop) REFERENCES dbo.Lop(ID)
)
GO

CREATE TABLE ThongBaoHS
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	NoiDung NVARCHAR(MAX),
	Ngay DATE,
	IDLoaiThongBao INT,

	FOREIGN KEY (IDLoaiThongBao) REFERENCES dbo.LoaiThongBao(ID),
	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO
CREATE TABLE PhanCongDay
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDGiaoVien INT,
	IDLop INT,
	IDMonHoc INT,

	FOREIGN KEY (IDGiaoVien) REFERENCES dbo.TaiKhoanTruong(ID),
	FOREIGN KEY (IDLop) REFERENCES dbo.Lop(ID),
	FOREIGN KEY (IDMonHoc) REFERENCES dbo.MonHoc(ID)
)
GO	

CREATE TABLE GVCN
(
	IDLop INT,
	IDGiaoVien INT,

	PRIMARY KEY(IDLop,IDGiaoVien),
	FOREIGN KEY (IDLop) REFERENCES dbo.Lop(ID),
	FOREIGN KEY (IDGiaoVien) REFERENCES dbo.TaiKhoanTruong(ID)
)
GO

CREATE TABLE TenHocPhi
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Thang INT,
	TienHoc INT,
	TienAn INT,
	TienDien INT,
	TienNuoc INT,
	TienVeSinh INT,
	TienTrangThietBi INT,
	TienTaiLieu INT
)
GO

CREATE TABLE BHYT 
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDHocSinh INT,
	DangKy BIT	DEFAULT 0,
	BHQD BIT DEFAULT 0,

	FOREIGN KEY (IDHocSinh) REFERENCES dbo.ThongTinHS(ID)
)
GO	